export const SET_CITY = 'SET_CITY';
export const SET_GOODS = 'SET_GOODS';
export const GET_SHOPLIST_INDEX = 'GET_SHOPLIST_INDEX';
export const SET_LOGINSTAUTS = 'SET_LOGINSTAUTS';
export const SET_FOODCARTLIST = 'SET_FOODCARTLIST';



